### ISSUE TITLE
Problem to find module

### ISSUE THREAD

**Issue by viniblima** [tj/node-migrate#170]
When I import from node_modules, show the error "Could not find a declaration file for module 'migrate"

**Comment by wesleytodd** [comment]
"Declaration file" sounds like TypeScript.  Guessing that is because this module is not typed.  You might want to post some logs and information about your setup to be sure.  If it is TS and you want to submit types please open a PR.

**Comment by viniblima** [comment]
its a simple "const migrate = require('migrate');"

**Comment by viniblima** [comment]
I already installed migrate with "npm i migrate" and "npm i --save migrate";

**Comment by wesleytodd** [comment]
Post a repo or show your actual log output. I cannot help otherwise.

**Comment by viniblima** [comment]
https://github.com/viniblima/ecommerce-admin-express/blob/master/bin/migrate.js

**Comment by wesleytodd** [comment]
Nothing obviously wrong with this implementation. Post logs and instructions to reproduce

**Comment by viniblima** [comment]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'migrate'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/bin/migrate.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ecommerce-admin@1.0.0 migrate: `node ./bin/migrate.js "up"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ecommerce-admin@1.0.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-16T01_15_30_542Z-debug.log

**Comment by wesleytodd** [comment]
This says you do not have the module installed.  Run npm install

**Comment by viniblima** [comment]
the error was ond docker, sorry
