### ISSUE TITLE
v1 does not respect old migration state file format

### ISSUE THREAD

**Issue by ryanrolds** [tj/node-migrate#90]
When running migrations with a pre-v1 migration state file in v1, `migrate` ignores the old format and attempts to run all migrations in the migration directory. which is poor behavior. If the format of the file is not what is expected it should error, otherwise the database is at risk of being placed in an invalid state. Consuming and migrating the old format to the new format may be preferred.

**Comment by wesleytodd** [comment]
I can get on board with your suggestion for it to migrate the old format.  I agree the current lack of a migration path for pre 1 users is not good, but is is better than the outright broken behavior of the pre 1 state file, thus the change.

Want to make a PR?  If not I might not be able to get to it for a few days otherwise, but I will be able to review and publish if you can put together something good.

**Comment by ryanrolds** [comment]
Yes, I will make PR for this. Hopefully will have it tomorrow. Thankfully we caught this on release to our test env. :)

**Comment by wesleytodd** [comment]
Good to hear!! I would find it hard to have sympathy for anyone who ran this on a production setup without testing after doing a major version update, but I certainly see your concern.  

I had left open the 1.x beta for months trying to solicit feedback before publishing, but didn't get much, so sorry for not noticing the migration plan gap which is here.  It was just not a problem I directly had.

**Comment by ryanrolds** [comment]
Trying to make sure tests pass before starting work on the PR, but they are not. What am I doing wrong?

```
$ npm test

> migrate@1.0.0 test /home/ryan/repos/node-migrate
> standard && standard ./bin/* && mocha



  migration set
    ✓ should handle basic migration
    ✓ should add a new migration
    ✓ should emit events
    ✓ should migrate to named migration
    ✓ should load migration descriptions

  $ migrate
    init
      ✓ should create a migrations directory (69ms)
    create
      ✓ should create a fixture file (153ms)
      ✓ should respect the --date-format (166ms)
      ✓ should respect the --extention (156ms)
      ✓ should fail with non-zero and a helpful message when template is unreadable (152ms)
    up
      1) should run up on multiple migrations
      2) should run up to a specified migration
      3) should run up multiple times
      4) should run down when passed --clean
    down
      5) should run down on multiple migrations
      6) should run down to a specified migration
      7) should run down multiple times
    list
      8) should list available migrations

  integration tests
    ✓ should warn when the migrations are run out of order (672ms)
    ✓ should error when migrations are present in the state file, but not loadable (669ms)
    9) should load the enviroment file when passed --env

  issue #33
    ✓ should run migrations in the correct order

  Promise migrations
    ✓ should handle callback migration
    ✓ should handle promise migration
    ✓ should warn when using promise but still calling callback
    ✓ should warn with no promise or callback
    ✓ should error with rejected promises


  18 passing (3s)
  9 failing

  1) $ migrate up should run up on multiple migrations:

      Uncaught AssertionError: 1 == 0
      + expected - actual

      -1
      +0
      
      at test/cli.js:115:16
      at ChildProcess.<anonymous> (test/util/run.js:16:5)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

  2) $ migrate up should run up to a specified migration:

      Uncaught AssertionError: 1 == 0
      + expected - actual

      -1
      +0
      
      at test/cli.js:128:16
      at ChildProcess.<anonymous> (test/util/run.js:16:5)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

  3) $ migrate up should run up multiple times:

      Uncaught AssertionError: 1 == 0
      + expected - actual

      -1
      +0
      
      at test/cli.js:141:16
      at ChildProcess.<anonymous> (test/util/run.js:16:5)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

  4) $ migrate up should run down when passed --clean:

      Uncaught AssertionError: 1 == 0
      + expected - actual

      -1
      +0
      
      at test/cli.js:156:16
      at ChildProcess.<anonymous> (test/util/run.js:16:5)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

  5) $ migrate down should run down on multiple migrations:

      Uncaught AssertionError: 1 == 0
      + expected - actual

      -1
      +0
      
      at test/cli.js:176:16
      at ChildProcess.<anonymous> (test/util/run.js:16:5)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

  6) $ migrate down should run down to a specified migration:

      Uncaught AssertionError: 1 == 0
      + expected - actual

      -1
      +0
      
      at test/cli.js:189:16
      at ChildProcess.<anonymous> (test/util/run.js:16:5)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

  7) $ migrate down should run down multiple times:

      Uncaught AssertionError: 1 == 0
      + expected - actual

      -1
      +0
      
      at test/cli.js:202:16
      at ChildProcess.<anonymous> (test/util/run.js:16:5)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

  8) $ migrate list should list available migrations:

      Uncaught AssertionError:   error : Error: ENOENT: no such file or directory, scandir '/home/ryan/repos/node-migrate/test/fixtures/numbers/migrations'

      + expected - actual

      -1
      +0
      
      at test/cli.js:219:16
      at ChildProcess.<anonymous> (test/util/run.js:16:5)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

  9) integration tests should load the enviroment file when passed --env:

      Uncaught AssertionError: 1 == 0
      + expected - actual

      -1
      +0
      
      at test/integration.js:106:14
      at ChildProcess.<anonymous> (test/util/run.js:16:5)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
```

**Comment by wesleytodd** [comment]
Nothing AFAICT.  They worked when this was published a few weeks ago, but they failed for me on a fresh clone and install.  Looking now.

**Comment by ryanrolds** [comment]
Thanks.

**Comment by wesleytodd** [comment]
There was an old and invalid `.gitignore` rule which caused the tests to pass on my other machine.  Now that is removed and pushed/published.  Tests passed for me again after a `git clean -fdx && npm it`.  See 738dbcda4930f511716fd2e4a2b11b1d1292f14d

**Comment by ryanrolds** [comment]
Thanks. Confirming that tests pass on a fresh checkout. I will work up a PR tomorrow.
